version: "0.1.0"

services:
  web_server:
    build:
      context: .
      dockerfile: ./Dockerfile.Web
      args:
        - SERVER_URI_PANDAS=${SERVER_URI_PANDAS}
    container_name: web_server
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file: .env
    # environment: 
      # - SERVER_URI_PANDAS=${SERVER_URI_PANDAS}

  pandas_server:
    build:
      context: .
      dockerfile: ./Dockerfile.Pandas
    container_name: pandas_server
    restart: always
    ports:
      - "${PANDAS_PORT}:4000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # env_file: .env
    environment: 
      - REDIS_HOST=${PANDAS_REDIS_HOST}
      - REDIS_PORT=${PANDAS_REDIS_PORT}
      - REDIS_PASSWORD=${PANDAS_REDIS_PASSWORD}
      - HOST=0.0.0.0
      - PORT=4000

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    # env_file: .env

# explicit env_file
# docker-compose --env-file ./.env up -d
# docker-compose up -d --build
# redis-cli -h 127.0.0.1 -p 5001 -a dosimpact
