FROM node:16

ARG SERVER_URI_PANDAS http://0.0.0.0:4000

ENV APP_ROOT /app
ENV NODE_ENV production
ENV WEB_PORT 80
ENV SERVER_URI_PANDAS ${SERVER_URI_PANDAS}

# validation
RUN if [  -z $SERVER_URI_PANDAS ];then \
  >&2 echo "[Warning] SERVER_URI_PANDAS seems empty" ; else\
  >&2 echo "SERVER_URI_PANDAS=" $SERVER_URI_PANDAS; \
  fi

# setup - workdir
RUN mkdir -p ${APP_ROOT}
ADD ./ ${APP_ROOT}
WORKDIR ${APP_ROOT}

# install client and node

RUN cd server_node && yarn install
RUN cd client && yarn install
RUN cd client && yarn build

EXPOSE 3000

CMD ["npm","run","start:client"]

# docker run --rm -it --name node_web node:16 bash
# docker run -itd --name node_web node:16 
# docker build --build-arg http://dosimpact.iptime.org:34000 -t ehdudtkatka/quant-coin-web:0.1.1 -f Dockerfile.Web .
# docker push ehdudtkatka/quant-coin-web:0.1.1


